SmallBusinessManagementSystem/SmallBusinessManagementSystem/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmallBusinessManagementSystem.BLL.CategoryManager;
using SmallBusinessManagementSystem.Models.Models;


namespace SmallBusinessManagementSystem.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager _manager=new CategoryManager();
        public ActionResult Index()
        {
            return View();
        }

     
        public ActionResult GetCategories()
        {
            var categories = _manager.GetCategories();
            return Json(new { data = categories }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]

        public ActionResult Save(int id)
        {
            var category = _manager.Save(id);
            return View(category);
        }
      
        [HttpPost]
        public ActionResult Save(Category category)
        {
            int status = 0;
            bool isSaved = false;
            if (ModelState.IsValid)
            {
                status = _manager.SaveByPost(category);
            }
            if (status > 0)
            {
                isSaved = true;
            }

            return new JsonResult { Data = new { isSaved = isSaved } };
        }

        [HttpGet]

        public ActionResult Delete(int id)
        {
            var v = _manager.Delete(id);
            if (v != null)
            {
                return View(v);
            }
            else
            {
                return HttpNotFound();
            }
            
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteCategory(int id)
        {
            bool isSaved = false;
            int status = _manager.DeleteCategory(id);
            if (status > 0)
            {
                isSaved = true;
            }
            return new JsonResult { Data = new { isSaved = isSaved } };
        }
    }
}

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmallBusinessManagementSystem.BLL.ProductManager;
using SmallBusinessManagementSystem.Models.Models;

namespace SmallBusinessManagementSystem.Controllers
{
    public class ProductController : Controller
    {
        ProductManager _manager=new ProductManager();
        static private HttpPostedFileBase image;
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult GetProducts()
        {
            var products = _manager.GetProducts();
            return Json(new { data = products }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]

        public ActionResult Save(int id)
        {
            var products = _manager.Save(id);
            ViewBag.CategoryId = _manager.GetCategoryList();
           
            return View(products);
        }
        [HttpPost]
        public void Upload(Product product)
       {
         if (product.ImageFile != null && product.ImageFile.ContentLength > 0)
         {
             image = product.ImageFile;
         }
}

        [HttpPost]
        public ActionResult Save(Product product)
        {
            product.ImageFile = image;
            int status = 0;
            bool isSaved = false;
            if (ModelState.IsValid)
            {
                
                status = _manager.SaveByPost(product);
            }
            if (status > 0)
            {
                isSaved = true;
            }

            return new JsonResult { Data = new { isSaved = isSaved } };
            
        }

        [HttpGet]

        public ActionResult Delete(int id)
        {
            var v = _manager.Delete(id);
            if (v != null)
            {
                return View(v);
            }
            else
            {
                return HttpNotFound();
            }

        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteProduct(int id)
        {
            bool isSaved = false;
            int status = _manager.DeleteProduct(id);
            if (status > 0)
            {
                isSaved = true;
            }

            return new JsonResult { Data = new { isSaved = isSaved } };
        }

        [HttpGet]
        public ActionResult ProductImageView(int id)
        {
            Product product = new Product();

            //using (DbModels db = new DbModels())
            //  {
            //imageModel = db.Images.Where(x => x.ImageID == id).FirstOrDefault();
            //  }
            product = _manager.GetImageView(id);

            return View(product);
        }
    }
}

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmallBusinessManagementSystem.BLL.PurchaseManager;
using SmallBusinessManagementSystem.Models.Models;

namespace SmallBusinessManagementSystem.Controllers
{
    public class PurchaseController : Controller
    {
        PurchaseManager _manager=new PurchaseManager();
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Purchase purchase)
        {
            if (ModelState.IsValid && purchase.PurchaseDetailses != null && purchase.PurchaseDetailses.Count > 0)
            {
                var isAdded = _manager.Add(purchase);
                if (isAdded)
                {
                    return View(purchase);
                }

                
            }
            return View();
        }
        
    }
}

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmallBusinessManagementSystem.BLL.SalesManager;
using SmallBusinessManagementSystem.Models.Models;

namespace SmallBusinessManagementSystem.Controllers
{
    public class SalesController : Controller
    {
        SalesManager _manager=new SalesManager();
       [HttpGet] 
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
       public ActionResult Create(Sales sales)
       {
           if (ModelState.IsValid && sales.SalesDetailses != null && sales.SalesDetailses.Count > 0)
           {
               var isAdded = _manager.Add(sales);
               if (isAdded)
               {
                   return View(sales);
               }


           }
           return View();
       }
    }
}

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace SmallBusinessManagementSystem.Controllers
{
    public class SecurityController : Controller
    {
        // GET: Security
       [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        
        [Authorize]
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult My()
        {
            return View();
        }

[HttpPost]
        public ActionResult CheckUser()
        {
    if (Request.Form["Email"] == "user@gmail.com" && Request.Form["Password"] == "Password")
    {
        FormsAuthentication.SetAuthCookie(Request.Form["Email"],true);
        return RedirectToAction("Home");
    }
            else
            {
                return View("Login");
            }
        }
    }
}

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Category/Delete.cshtml
@model SmallBusinessManagementSystem.Models.Models.Category

<h2>Delete Employee</h2>
@using (Html.BeginForm("delete", "Category", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.CategoryId)
    <div class="form-group">
        <label>Category Code</label>
        <p>@Model.Code</p>
    </div>

    <div class="form-group">
        <label>Category Name</label>
        <p>@Model.Name</p>
    </div>

   
    <div>
        <input type="submit" value="Delete" />
    </div>
}

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Category/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Category Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet"/>
    
    <style>
        span.field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div style="width:90%; margin:0 auto" class="tablecontainer">
        <a class="popup btn btn-primary" href="/category/save/0" style="margin-bottom:20px; margin-top:20px;">Add New Category</a>
        <table id="myDatatable">
            <thead>
                <tr>
                    <th>Category Code</th>
                    <th>Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
        </table>
    </div>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script src="~/Scripts/SmallBusinessManagementSystem/CategoryIndex/CategoryIndex.js"></script>
    

    
</body>
</html>

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Category/Save.cshtml
@model SmallBusinessManagementSystem.Models.Models.Category

<h2>Save</h2>
@using (Html.BeginForm("save", "Category", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.CategoryId > 0)
    {
        @Html.HiddenFor(a => a.CategoryId)
    }

    <div class="form-group">
        <label>Category Code</label>
        @Html.TextBoxFor(a => a.Code, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Code)
    </div>
    <div class="form-group">
        <label>Category Name</label>
        @Html.TextBoxFor(a => a.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Name)
    </div>
   
    <div>
        <input type="submit" value="Save" />
    </div>
}

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Product/Delete.cshtml
@model SmallBusinessManagementSystem.Models.Models.Product

<h2>Delete Product</h2>
@using (Html.BeginForm("delete", "Product", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.ProductId)
    <div class="form-group">
        <label>Product Code</label>
        <p>@Model.Code</p>
    </div>

    <div class="form-group">
        <label>Product Name</label>
        <p>@Model.Name</p>
    </div>


    <div>
        <input type="submit" value="Delete" />
    </div>
}

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Product/Index.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Product Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <style>
        span.field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div style="width:90%; margin:0 auto" class="tablecontainer">
        <a class="popup btn btn-primary" href="/product/save/0" style="margin-bottom:20px; margin-top:20px;">Add New Product</a>
        <table id="myDatatable">
            <thead>
                <tr>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Category Id</th>
                    <th>Reorder Level</th>
                    <th>Description</th>
                    <th>Image</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
        </table>
    </div>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/SmallBusinessManagementSystem/ProductIndex/ProductIndex.js"></script>
    



</body>
</html>

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Product/ProductImageView.cshtml
@model SmallBusinessManagementSystem.Models.Models.Product

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">


        <dd>
            <img src="@Url.Content(Model.ImagePath)" width="250" height="250" multiple />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Product/Save.cshtml
@model SmallBusinessManagementSystem.Models.Models.Product
<style type="text/css">.popupForm { }</style>

<h2>Save</h2>
@using (Html.BeginForm("Save", "Product", FormMethod.Post, new { id = "popupForm" }))

{
    if (Model != null && Model.ProductId > 0)
    {
        @Html.HiddenFor(a => a.ProductId)
    }

    <div class="form-group">
        <label>Product Code</label>
        @Html.TextBoxFor(a => a.Code, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Code)
    </div>
    <div class="form-group">
        <label>Product Name</label>
        @Html.TextBoxFor(a => a.Name, new {@class = "form-control"})
        @Html.ValidationMessageFor(a => a.Name)
    </div>
    <div class="form-group">
       @Html.LabelFor(model => model.CategoryId, "CategoryId", new { @class = "control-label col-md-2" })
        @Html.DropDownList("CategoryId", String.Empty)
        @Html.ValidationMessageFor(a => a.CategoryId)
    </div>
    <div class="form-group">
        <label>Reorder Level</label>
        @Html.TextBoxFor(a => a.ReorderLevel, new {@class = "form-control"})
        @Html.ValidationMessageFor(a => a.ReorderLevel)
    </div>
    <div class="form-group">
        <label>Description</label>
        @Html.TextBoxFor(a => a.Description, new {@class = "form-control"})
        @Html.ValidationMessageFor(a => a.Description)
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.ImagePath, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="ImageFile" name="ImageFile" required>
        </div>
    </div>

    <div>
        <input type="submit" name="btn" value="Save" />
    </div>
}
<script type="text/javascript">

    function FileUploadClick() {

        var formData = new FormData();
        var totalFiles = document.getElementById("ImageFile").files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = document.getElementById("ImageFile").files[i];

            formData.append("ImageFile", file);
        }

        $.ajax({
            type: "POST",
            url: '/product/Upload',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false,
            success: function (response) {
                alert('succes!!');
            },
            error: function (error) {
                alert("errror");
            }
        });
    }

    $(function () {
     $("input:file").change(function () {
         alert("File choosen");
         FileUploadClick();

     });
  });
</script>

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Purchase/Add.cshtml
@model SmallBusinessManagementSystem.Models.Models.Purchase



@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Category Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <style>
        span.field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="panel-group">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="panel-title">Puchase Header</div>
                </div>

                <div class="panel-body">
                    <div class="form-group row">
                        @Html.LabelFor(m => m.Date, "Date", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.Date, null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(m => m.InvoiceNumber, "Invoice Number", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.InvoiceNumber, null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(m => m.PurchaseSupplierId, "Supplier", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.PurchaseSupplierId, null, new { @class = "form-control" })
                        </div>


                    </div>


                </div>



            </div>



        </div>

        <div class="panel-group">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="panel-title">Puchase Details</div>
                </div>

                <div class="panel-body">
                    <div class="form-group row">
                        @Html.Label("PurchaseProductId", "Product Id", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchaseProductId", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchaseProductCode", "Product Code", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchaseProductCode", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchaseManufacturedDate", "Manufactured Date", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchaseManufacturedDate", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchaseExpireDate", "Expire Date", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchaseExpireDate", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchaseQty", "Purchase Quantity", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchaseQty", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchaseUnitPrice", "Unit Price", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchaseUnitPrice", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchaseTotalPrice", "Total Price", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchaseTotalPrice", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchasePreviousPrice", "Previous Cost Price", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchasePreviousPrice", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchasePreviousMRP", "Previous MRP", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchasePreviousMRP", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchaseNewCostPrice", "New Cost Price", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchaseNewCostPrice", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("PurchaseNewMRP", "New MRP", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("PurchaseNewMRP", null, new { @class = "form-control" })
                        </div>


                    </div>

                    <div>
                        <input type="button" id="AddButton" value="Add" class="btn btn-info" />
                    </div>



                </div>



            </div>



        </div>
        <div class="panel-group">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="panel-title">Added Puchase Details</div>
                </div>

                <div class="panel-body">

                    <table class="table table-bordered table-hover table-striped table-responsive">

                        <thead>
                            <tr style="background-color: green; color: white; font-weight: bold">
                                <td>Sl</td>
                                <td>Products(Code)</td>
                                <td>Manufactured Date</td>
                                <td>Expire Date</td>
                                <td>Purchased Quantity</td>
                                <td>Unit Price</td>
                                <td>Total Price</td>
                                <td>Previous CP</td>
                                <td>Precious MRP</td>
                                <td>New CP</td>
                                <td>New MRP</td>
                            </tr>
                        </thead>
                        <tbody id="PurchaseDetailsTable"></tbody>

                    </table>



                </div>



            </div>

        </div>

        <div class="col-md-4 col-md-offset-4">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    }

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>


    <script src="~/Scripts/SmallBusinessManagementSystem/Purchase/PurchaseCreate.js"></script>



</body>
</html>

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Sales/Create.cshtml
@model SmallBusinessManagementSystem.Models.Models.Sales



@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Category Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <style>
        span.field-validation-error {
            color: red;
        }
    </style>
</head>
<body>

    @using (Html.BeginForm())
    {
        
        <div class="panel-group">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="panel-title">Puchase Header</div>
                </div>

                <div class="panel-body">
                    <div class="form-group row">
                        @Html.LabelFor(m => m.CustomerId, "Customer", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.CustomerId, null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(m => m.Date, "Date", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.Date, null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(m => m.EarnedLoyalityPoint, "Loyality Point", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(m => m.EarnedLoyalityPoint, null, new { @class = "form-control" })
                        </div>


                    </div>


                </div>



            </div>



        </div>

        <div class="panel-group">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="panel-title">Puchase Details</div>
                </div>

                <div class="panel-body">
                    <div class="form-group row">
                        @Html.Label("SalesProductId", "Product", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("SalesProductId", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("SalesAvailableQuantity", "Available Quantity", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("SalesAvailableQuantity", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("SalesQuantity", "Quantity", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("SalesQuantity", null, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group row">
                        @Html.Label("SalesUnitPrice", "Unit Price", new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.TextBox("SalesUnitPrice", null, new { @class = "form-control" })
                        </div>


                    </div>
                   
            

                    <div>
                        <input type="button" id="AddButton" value="Add" class="btn btn-info" />
                    </div>



                </div>



            </div>



        </div>
        <div class="panel-group">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="panel-title">Added Product Details</div>
                </div>

                <div class="panel-body">

                    <table class="table table-bordered table-hover table-striped table-responsive">

                        <thead>
                            <tr style="background-color: green; color: white; font-weight: bold">
                                <td>Sl</td>
                                <td>Product</td>
                                <td>Quantity</td>
                                <td>Unit Price</td>
                                <td>Total Price</td>
                                
                            </tr>
                        </thead>
                        <tbody id="SalesDetailsTable"></tbody>

                    </table>



                </div>



            </div>

        </div>

        <div class="col-md-4 col-md-offset-4">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    }

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script src="~/Scripts/SmallBusinessManagementSystem/Sales/SalesCreate.js"></script>
   



</body>
</html>

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Security/Home.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
</head>
<body>
<div>
    <p>Hello! Welcome</p>
</div>
</body>
</html>

SmallBusinessManagementSystem/SmallBusinessManagementSystem/Views/Security/My.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>My</title>
</head>
<body>
<div>
    My
</div>

</body>
</html>